// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpkCHaA7dyrQrX8qjJot7T2GdHankDsuQ',
    appId: '1:1091507683273:web:60bc015dcc1aeda0c7f218',
    messagingSenderId: '1091507683273',
    projectId: 'fb-volkov-login',
    authDomain: 'fb-volkov-login.firebaseapp.com',
    storageBucket: 'fb-volkov-login.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRF0bjtNDAr969c6zD_boinyTLPRObDwc',
    appId: '1:1091507683273:android:f244e029645e93b2c7f218',
    messagingSenderId: '1091507683273',
    projectId: 'fb-volkov-login',
    storageBucket: 'fb-volkov-login.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeqwzMbalEGuKm3rMFIjveCUYYE514AFA',
    appId: '1:1091507683273:ios:e80e2e302fb214a9c7f218',
    messagingSenderId: '1091507683273',
    projectId: 'fb-volkov-login',
    storageBucket: 'fb-volkov-login.appspot.com',
    iosClientId: '1091507683273-8e47olojntcjbh94rkusm171lhvqk0kj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeqwzMbalEGuKm3rMFIjveCUYYE514AFA',
    appId: '1:1091507683273:ios:e80e2e302fb214a9c7f218',
    messagingSenderId: '1091507683273',
    projectId: 'fb-volkov-login',
    storageBucket: 'fb-volkov-login.appspot.com',
    iosClientId: '1091507683273-8e47olojntcjbh94rkusm171lhvqk0kj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
